export const stations = [
  // Harbour Line Stations
  { name: "Panvel", line: "Harbour" },
  { name: "Khandeshwar", line: "Harbour" },
  { name: "Manasarovar", line: "Harbour" },
  { name: "Kharghar", line: "Harbour" },
  { name: "Belapur CBD", line: "Harbour" },
  { name: "Seawoods Darave", line: "Harbour" },
  { name: "Nerul", line: "Harbour" },
  { name: "Juinagar", line: "Harbour" },
  { name: "Sanpada", line: "Harbour" },
  { name: "Vashi", line: "Harbour" },
  { name: "Mankhurd", line: "Harbour" },
  { name: "Govandi", line: "Harbour" },
  { name: "Chembur", line: "Harbour" },
  { name: "Tilak Nagar", line: "Harbour" },
  { name: "Kurla", line: "Harbour" },
  { name: "Chunabhatti", line: "Harbour" },
  { name: "GTB Nagar", line: "Harbour" },
  { name: "Dockyard Road", line: "Harbour" },
  { name: "Reay Road", line: "Harbour" },
  { name: "Cotton Green", line: "Harbour" },
  { name: "Sewri", line: "Harbour" },
  { name: "Wadala Road", line: "Harbour" },
  { name: "King's Circle", line: "Harbour" },
  { name: "Mahim", line: "Harbour" },
  { name: "Bandra", line: "Harbour" },
  { name: "Khar Road", line: "Harbour" },
  { name: "Santacruz", line: "Harbour" },
  { name: "Vile Parle", line: "Harbour" },
  { name: "Andheri", line: "Harbour" },
  { name: "Jogeshwari", line: "Harbour" },
  { name: "Goregaon", line: "Harbour" },

  // Central Line Stations
  { name: "CSMT", line: "Central" },
  { name: "Masjid", line: "Central" },
  { name: "Sandhurst Road", line: "Central" },
  { name: "Byculla", line: "Central" },
  { name: "Chinchpokli", line: "Central" },
  { name: "Currey Road", line: "Central" },
  { name: "Parel", line: "Central" },
  { name: "Dadar", line: "Central" },
  { name: "Matunga", line: "Central" },
  { name: "Sion", line: "Central" },
  { name: "Kurla", line: "Central" },
  { name: "Vidya Vihar", line: "Central" },
  { name: "Ghatkopar", line: "Central" },
  { name: "Vikhroli", line: "Central" },
  { name: "Kanjurmarg", line: "Central" },
  { name: "Bhandup", line: "Central" },
  { name: "Nahur", line: "Central" },
  { name: "Mulund", line: "Central" },
  { name: "Thane", line: "Central" },
  { name: "Kalwa", line: "Central" },
  { name: "Mumbra", line: "Central" },
  { name: "Diva", line: "Central" },
  { name: "Kopar", line: "Central" },
  { name: "Dombivli", line: "Central" },
  { name: "Thakurli", line: "Central" },
  { name: "Kalyan", line: "Central" },

  // Western Line Stations
  { name: "Churchgate", line: "Western" },
  { name: "Marine Lines", line: "Western" },
  { name: "Charni Road", line: "Western" },
  { name: "Grant Road", line: "Western" },
  { name: "Mumbai Central", line: "Western" },
  { name: "Mahalaxmi", line: "Western" },
  { name: "Lower Parel", line: "Western" },
  { name: "Elphinstone Road", line: "Western" },
  { name: "Dadar", line: "Western" },
  { name: "Matunga Road", line: "Western" },
  { name: "Mahim", line: "Western" },
  { name: "Bandra", line: "Western" },
  { name: "Khar Road", line: "Western" },
  { name: "Santacruz", line: "Western" },
  { name: "Vile Parle", line: "Western" },
  { name: "Andheri", line: "Western" },
  { name: "Jogeshwari", line: "Western" },
  { name: "Goregaon", line: "Western" },
  { name: "Malad", line: "Western" },
  { name: "Kandivali", line: "Western" },
  { name: "Borivali", line: "Western" },
  { name: "Dahisar", line: "Western" },
  { name: "Mira Road", line: "Western" },
  { name: "Bhayandar", line: "Western" },
  { name: "Naigaon", line: "Western" },
  { name: "Vasai Road", line: "Western" },
  { name: "Nalasopara", line: "Western" },
  { name: "Virar", line: "Western" }
];